import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/Header";

const manorepo = Manrope({
  weight: ["500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "PetLove",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manorepo.className}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
